query getPost($uuid: String!) {
  posts(uuid: $uuid) {
    uuid
    PublishDate
    Title
    Text
    Photo
    Tags
  	Owner {
      username
      photo
    }
    Category
    Approvals {
      name
    }
    Declines {
      name
    }
    Comments {
      name
      post {
        uuid
      }
      user {
        username
        photo
      }
      Time
      Text
    }
     Objections {
      edges {
        node {
          PublishDate
          Owner {
            username
            photo
          }
          Title
          uuid
        }
      }
    }
  }
}