query getPost($username: String!) {
  posts(Owner: $username) {
    uuid
    PublishDate
    Title
    Photo
    ObjectionTo
  	Owner {
      username
    }
    Category
    Approvals {
      name
    }
    Declines {
      name
    }
     Comments {
      name
      post {
        uuid
      }
      user {
        username
        photo
      }
      Time
      Text
    }
    Objections {
			totalCount
    }
} 
}