query getProfile($username: String!) {
  accounts(Username: $username){
    username
        firstName
        lastName
        bio
        photo
        Approvals {
            name
            Time
            post {
                Title
                uuid
                Owner {
                    username
                    photo
                }
            }
        }
  }
}
  