query getRandomPost($uuid: String!) {
  randomPost(uuid: $uuid) {
    uuid
    PublishDate
    Title
    Text
    Photo
    Tags
  	Owner {
      username
      photo
    }
    Category
    Approvals {
      name
    }
    Declines {
      name
    }
    Comments {
      name
      post {
        uuid
      }
      user {
        username
        photo
      }
      Time
      Text
    }
    
  }
}
